# Site settings
title: Graphic Design
email: joke@jokedewinter.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Graphic design portfolio from the three month graphic design course at Shillington in New York.
baseurl: '/design'
url: ""
twitter_username: jokedewinter
github_username:  jokedewinter

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Pretty permalinks for posts
collections:
posts:
output: true
permalink: /:title/

# Sass compiling
sass:
    sass_dir: _sass
    style: compressed

# Exclude from processing.
exclude:
- Gemfile
- Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
- vendor
- .sass-cache